---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts":
    get:
      summary: list posts
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: posts found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
